# 10. Temporal Trends in Survival

## 10.1 Lamb Survival Trend

```{r}
#| label: trend-surv-lamb-calc
#| echo: true
#| eval: true

# Fit long-term survival trend for lambs
Survival_lamb_trend <- brm(
  Survival ~ Sex * (wtd114 + pop_den + Year_trend) + (1 | Yr),  
  data = Data_lamb_scaled, 
  family = bernoulli(link = "logit"), 
  cores = 4, chains = 4, warmup = 4000, iter = 10000, 
  threads = threading(2), backend = "cmdstanr", seed = 408502552
)
```

```{r}
#| label: trend-surv-lamb-results
#| echo: true
#| eval: true

summary(Survival_lamb_trend)
p_direction(Survival_lamb_trend)
pp_check(Survival_lamb_trend, ndraws = 100, type = "bars")
lamb_trend_powerscale <- powerscale_sensitivity(Survival_lamb_trend)

ft_lamb_trend <- flextable(extract_brms_summary(Survival_lamb_trend, "Lamb")) |> autofit()
doc <- read_docx()       
doc <- body_add_flextable(doc, ft_lamb_trend)   
print(doc, target = "lamb_trend.docx")
```

```{r}
#| label: trend-surv-lamb-plots
#| echo: true
#| eval: true

ce_lamb_trend <- conditional_effects(Survival_lamb_trend, effects = "Year_trend", resp = "Survival")
plot_lamb_trend <- ce_lamb_trend$`Year_trend`

data_mean_lamb_trend <- Data_lamb_scaled |>
  group_by(Year_trend) |>
  summarise(
    survival_rate = mean(Survival, na.rm = TRUE), 
    n = n(),                                      
    .groups = "drop"
  )

lamb_trend <- ggplot(plot_lamb_trend, aes(x = Year_trend, y = estimate__)) +
  geom_point(
    data = data_mean_lamb_trend, 
    aes(x = Year_trend, y = survival_rate, size = n), color = "#5c5f5d", 
    alpha = 0.2
  ) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__), fill = "#4575b4", alpha = 0.2) +
  geom_line(color = "#4575b4", linewidth = 1.5, lineend = "round") +
  labs(x = "Year", y = "Survival probability") +
  scale_x_continuous(
    breaks = seq(0, 44, by = 10), 
    labels = seq(1979, 2024, by = 10),
    limits = c(0, 44)
  ) +
  theme_pubr()

lamb_trend

max(plot_lamb_trend$estimate__) - min(plot_lamb_trend$estimate__)
```

## 10.2 Female Survival Trend

```{r}
#| label: trend-surv-female-calc
#| echo: true
#| eval: true

# Fit long-term survival trend for females
Survival_female_trend <- brm(
  Survival ~ ns(Age, 3) + wtd114 + pop_den + Year_trend + (1 | Yr),  
  data = Data_female_scaled, 
  family = bernoulli(link = "logit"), 
  cores = 4, chains = 4, warmup = 4000, iter = 10000, 
  threads = threading(2), backend = "cmdstanr", seed = 2108304296
)
```

```{r}
#| label: trend-surv-female-results
#| echo: true
#| eval: true

summary(Survival_female_trend)
p_direction(Survival_female_trend)
pp_check(Survival_female_trend, ndraws = 100, type = "bars")
female_trend_powerscale <- powerscale_sensitivity(Survival_female_trend)

ft_female_trend <- flextable(extract_brms_summary(Survival_female_trend, "Female")) |> autofit()
doc <- read_docx()       
doc <- body_add_flextable(doc, ft_female_trend)   
print(doc, target = "female_trend.docx")
```

```{r}
#| label: trend-surv-female-plots
#| echo: true
#| eval: true

ce_female_trend <- conditional_effects(Survival_female_trend, effects = "Year_trend", resp = "Survival")
plot_female_trend <- ce_female_trend$`Year_trend`

data_mean_female_trend <- Data_female_scaled |>
  group_by(Year_trend) |>
  summarise(
    survival_rate = mean(Survival, na.rm = TRUE), 
    n = n(),                                      
    .groups = "drop"
  )

female_trend <- ggplot(plot_female_trend, aes(x = Year_trend, y = estimate__)) +
  geom_point(
    data = data_mean_female_trend, 
    aes(x = Year_trend, y = survival_rate, size = n), color = "#5c5f5d", 
    alpha = 0.2
  ) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__), fill = "#4575b4", alpha = 0.2) +
  geom_line(color = "#4575b4", linewidth = 1.5, lineend = "round") +
  labs(x = "Year", y = "Survival probability") +
  scale_x_continuous(
    breaks = seq(0, 44, by = 10), 
    labels = seq(1979, 2024, by = 10),
    limits = c(0, 44)
  ) +
  theme_pubr()

female_trend

max(plot_female_trend$estimate__) - min(plot_female_trend$estimate__)
```

## 10.3 Male Survival Trend

```{r}
#| label: trend-surv-male-calc
#| echo: true
#| eval: false

# Fit long-term survival trend for males
Survival_male_trend <- brm(
  Survival ~ ns(Age, 3) + wtd114 + pop_den + Year_trend + (1 | Yr),  
  data = Data_male_scaled, 
  family = bernoulli(link = "logit"), 
  cores = 4, chains = 4, warmup = 4000, iter = 10000, 
  threads = threading(2), backend = "cmdstanr", seed = 1458135459
)
```

```{r}
#| label: trend-surv-male-results
#| echo: true
#| eval: true

summary(Survival_male_trend)
p_direction(Survival_male_trend)
pp_check(Survival_male_trend, ndraws = 100, type = "bars")
male_trend_powerscale <- powerscale_sensitivity(Survival_male_trend)

ft_male_trend <- flextable(extract_brms_summary(Survival_male_trend, "Male")) |> autofit()
doc <- read_docx()       
doc <- body_add_flextable(doc, ft_male_trend)   
print(doc, target = "male_trend.docx")
```

```{r}
#| label: trend-surv-male-plots
#| echo: true
#| eval: true

ce_male_trend <- conditional_effects(Survival_male_trend, effects = "Year_trend", resp = "Survival")
plot_male_trend <- ce_male_trend$`Year_trend`

data_mean_male_trend <- Data_male_scaled |>
  group_by(Year_trend) |>
  summarise(
    survival_rate = mean(Survival, na.rm = TRUE), 
    n = n(),                                      
    .groups = "drop"
  )

male_trend <- ggplot(plot_male_trend, aes(x = Year_trend, y = estimate__)) +
  geom_point(
    data = data_mean_male_trend, 
    aes(x = Year_trend, y = survival_rate, size = n), color = "#5c5f5d", 
    alpha = 0.2
  ) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__), fill = "#4575b4", alpha = 0.2) +
  geom_line(color = "#4575b4", linewidth = 1.5, lineend = "round") +
  labs(x = "Year", y = "Survival probability") +
  scale_x_continuous(
    breaks = seq(0, 44, by = 10), 
    labels = seq(1979, 2024, by = 10),
    limits = c(0, 44)
  ) +
  theme_pubr()

male_trend

max(plot_male_trend$estimate__) - min(plot_male_trend$estimate__)
```
